apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor

spec:
  endpoints:
    - port: http
      scrapeTimeout: 30s
      path: /actuator/prometheus
      honorLabels: true
      scheme: http
  #  jobLabel: stack
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: {{ .Release.Name }}