apiVersion: v1
kind: Service
metadata:
  name: otus-service
spec:
  selector:
    app: otus-homework
  ports:
    - protocol: TCP
      name: service-port
      port: 80
      targetPort: 8000
  type: ClusterIP