apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgresql-deployment
  namespace: otus-homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgresql
  template:
    metadata:
      labels:
        app: my-postgresql
    spec:
      containers:
        - name: my-postgresql
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: otusdb
            - name: POSTGRES_USER
              value: otususer
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgresql
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}