apiVersion: v1
kind: Service
metadata:
  name: my-postgresql
  namespace: otus-homework
spec:
  selector:
    app: my-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP